### ISSUE TITLE
Bug Report: Beaver Builder Post Grid ajax "Load More" and "Scrolling" load reloads initial query when this plugin is active

### ISSUE THREAD

**Issue by studioleland** [FacetWP/facetwp-beaver-builder#11]
Hello,

To test:

1. Using the default Post Grid Module of BB Agency (latest version).
2. Select custom post type
3. Choose "Load More"
4. More posts added but same post set as the initial load.  Repeats same initial query each time.
5. Disabling this plugin resolves issue.

**Comment by mgibbs189** [comment]
Thanks for reporting @studioleland. This has been fixed in the `master` branch (will be released this week).
