### ISSUE TITLE
How to setup this plugin

### ISSUE THREAD

**Issue by dlfdlf56** [FacetWP/facetwp-beaver-builder#2]
I installed this plugin on Wordpress 4.8 and Beaver Themer 1.0.1.2 and am able to create a template in FacetWP and a facet and when I put the shortcodes on a page they work just fine.  When I attempt to use the same facet on a custom post type template, the facet never populates.  According to the directions on Facet's website I need to add div class="facetwp-template" in the loop.  How do I accomplish this with Beaver Themer custom layouts?  I have allready tried adding the <div class=... to archive.php but that doesn't work either.  Any information you can provide on how to setup this plug-in would be greatly appreciated.

**Comment by dlfdlf56** [comment]
I figured it out.

Thanks

**Comment by marcelreschke** [comment]
@dlfdlf56 How did you do it?

I have added the Post Module on an BT Archive layout, enabled FacetWP in Post Module, added a Facet Module in another column and chose a Hierarchy Facet.

The Post Module still displays all posts from the post type no matter what im selecting in the facet.
