### ISSUE TITLE
Equal Heights not being applied with fwp/bb pagination

### ISSUE THREAD

**Issue by MikeGillihan** [FacetWP/facetwp-beaver-builder#6]
Not sure this is something you can fix on your end, but I thought I would submit an issue here as well as to BB.

Using a FacetWP enabled post-grid and setting Equal Heights to Yes. Pagination set to Numbers. Whenever I use the pagination controls to view page 2, 3, Next, etc. The posts are no longer equal heights.

It looks like the JS setting the height is not being triggered upon the AJAX(?) load of the FWP paginated posts. I imagine it's looking for on.load or something. The heights do reset and correct themselves when I manually change the window size.

![image](https://user-images.githubusercontent.com/1378365/33304403-3bc1b6b6-d3ce-11e7-97a3-94b0c455c97e.png)

**Comment by mgibbs189** [comment]
@MikeGillihan is this still an issue with the latest version of the add-on (1.0.8)?
