### ISSUE TITLE
Sort field not displaying

### ISSUE THREAD

**Issue by neilgee** [FacetWP/facetwp-beaver-builder#7]
Adding a FacetWP sort field via shortcode `[facetwp sort="true"]` in a text editor or HTML module is not rendering the sort field, just an empty `<div class="facetwp-sort"></div>`

This is done making a themer template for a singular page. Other facets are rendering OK just the sort.

Using WP 4.9.1
FacetWP - Beaver Builder 1.0.8
FacetWP - 3.1.1
Beaver Themer 1.0.3
Beaver Builder 2.0.4.1

**Comment by neilgee** [comment]
It does work when shortcode is structured this way  ```[facetwp facet="my_facet"]
[facetwp sort="true"]```

**Comment by mgibbs189** [comment]
@neilgee there _is_ a sort module. You're looking in the wrong place, a sort isn't a facet, hence why it doesn't appear in that dropdown.
