### ISSUE TITLE
Fatal error if using this and you deactivate or activate first

### ISSUE THREAD

**Issue by codente** [FacetWP/facetwp-beaver-builder#9]
If you activate or deactivate this add-on before activating FacetWP you get 

`PHP Fatal error:  Uncaught Error: Call to undefined function FWP()`

I would suspect there could be some sort of check done to avoid this fatal error.

**Comment by mgibbs189** [comment]
Thanks for reporting!

**Comment by codente** [comment]
I actually still get this issue with the latest version of the plugin. So here's what happens now:

If I activate this add-on without BB or Facet active, it's fine.  If I activate this add-on with BB active and not the main FacetWP plugin, then the fatal error occurs.

And that also goes for if you deactivate FacetWP before you deactivate this plugin.  Same fatal error exists
```[26-Jun-2018 13:28:08 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function FWP() in /var/www/bb2new.codente.com/htdocs/wp-content/plugins/facetwp-beaver-builder-1.1.0/modules/template/class-template.php:48```

**Comment by codente** [comment]
This is still an issue.

**Comment by mgibbs189** [comment]
@codente open up `facetwp-beaver-builder.php` and change line 53 from:

`if ( class_exists( 'FLBuilderModule' ) ) {`

to

`if ( class_exists( 'FLBuilderModule' ) && function_exists( 'FWP' ) ) {`

Does that resolve the issue for you?

**Comment by codente** [comment]
Yes

**Comment by mgibbs189** [comment]
@codente Thanks again, we've pushed a new fixed version :)

**Comment by codente** [comment]
Awesome, thank you!

**Comment by pixelloop** [comment]
I just experienced this issue with the latest version.

I found it under "Console" as I was trying to use the pagination on a page that no longer works. 

Any ideas if this was introduced again in the latest update of BB?
